### ISSUE TITLE
Multiple definition of vaultscript.h / records.h

### ISSUE THREAD

**Issue by Koncord** [foxtacles/vaultmp#137]
>Inventory.o:Inventory.cpp:(.bss+0x264): first defined here
>plugin.o:plugin.cpp:(.bss+0x260): multiple definition of `cGetCell'

**Comment by Smoria** [comment]
Are You trying to compile script? You can't use multiple object files for script, because vaultscript.h has some class and function implementations.

**Comment by Koncord** [comment]
Yes, I know. Still need to solve the problem fundamentally.
