### ISSUE TITLE
Missing packet files

### ISSUE THREAD

**Issue by Langerz82** [foxtacles/vaultmp#140]
Hello,

Some of the files are missing they are:

PacketExtensions.hpp

PacketFactory.hpp

PacketTypes.hpp

If you could add those files to the packet folder in the source that would be excellent.

Kind regards

Joshua L

**Comment by Langerz82** [comment]
Got source for them.

**Comment by foxtacles** [comment]
Just in case if other people encounter the problem: you have to initialize the git submodule to get the source
