### ISSUE TITLE
Project Wiki

### ISSUE THREAD

**Issue by BlackPhrase** [foxtacles/vaultmp#142]
Since vaultmp.com is now down is there any other way to access the VaultMP Wiki?
It would be good to move it here to the repo wiki

**Comment by foxtacles** [comment]
You can try the wayback machine: https://web.archive.org/web/20150115020856/http://www.vaultmp.com:80/showwiki.php

I could also make the website accessible again, but I'm generally hesitant about that - by now there's probably a bunch of security vulnerabilities known in the vB software/version that has been used, and I can't be bothered to take care of updating/securing it again

**Comment by Sh1ft0x0EF** [comment]
Can't access by your link above

Maybe you could please make an archive with the wiki pages and post it here then?
I'd be able to convert 'em into github wiki pages and publish here (if you enable wiki for this repo)
Thx

**Comment by foxtacles** [comment]
ok will do

**Comment by Sh1ft0x0EF** [comment]
@foxtacles , any news?

**Comment by foxtacles** [comment]
i will try to get to it this weekend

**Comment by Sh1ft0x0EF** [comment]
Alright, thx

**Comment by foxtacles** [comment]
here is a static version of the forum including the wiki: http://legacy.vaultmp.com/

**Comment by Sh1ft0x0EF** [comment]
Thank you
I'll start to port it right away

**Comment by Sh1ft0x0EF** [comment]
Scripting Wiki link is broken

**Comment by foxtacles** [comment]
http://legacy.vaultmp.com/showwiki.php@title=Special%253ACategories.html

should get into all pages from there

**Comment by Sh1ft0x0EF** [comment]
Is it possible to create a release from the latest available binaries from here?
http://legacy.vaultmp.com/showwiki.php@title=Download+binaries+source.html

**Comment by foxtacles** [comment]
https://github.com/foxtacles/vaultmp/releases/tag/gary2.9

**Comment by Sh1ft0x0EF** [comment]
These are binaries that equal to the current state of the sources, right?

**Comment by Sh1ft0x0EF** [comment]
And what we should do about the images? Should I copy them and put inside the repo to link to them?

**Comment by foxtacles** [comment]
actually no, these binaries reflect the state of this commit: https://github.com/foxtacles/vaultmp/commit/c7f37c51453a42ee52e016cdb0bb6a662206ab08

there hasn't been any newer versions released after anymore

**Comment by foxtacles** [comment]
you can reference assets like images from legacy.vaultmp.com if you want - if that's what you mean, no need to copy

**Comment by Sh1ft0x0EF** [comment]
Alright, but how can I reach a direct link to some image?

**Comment by foxtacles** [comment]
![image](https://user-images.githubusercontent.com/1135351/27769767-9ba3f5ce-5f31-11e7-92d9-571852bec5d4.png)
like that?

**Comment by Sh1ft0x0EF** [comment]
Yep

**Comment by Sh1ft0x0EF** [comment]
>actually no, these binaries reflect the state of this commit: c7f37c5
>
>there hasn't been any newer versions released after anymore

Well, this version could be attached to c7f37c5 and remain as latest available release atm

**Comment by Sh1ft0x0EF** [comment]
@foxtacles , I think that we should use Doxygen for all the API reference instead of porting it here
