### ISSUE TITLE
Weight reduction

### ISSUE THREAD

**Issue by BlackPhrase** [foxtacles/vaultmp#143]
I think that all precompiled dlls should be removed from the repo and archived and then shipped with release
This will be really helpful
It should free up about 20MB of space
These dlls are only needed at runtime anyway

**Comment by foxtacles** [comment]
yep I agree. create a pull request for this change if you want :)

**Comment by Sh1ft0x0EF** [comment]
Should I create it from my fork? It has updates from Koncord which wasn't applied here yet

**Comment by foxtacles** [comment]
hmm, ideally you should do this:

1) checkout the tip of this repositories `master` https://github.com/foxtacles/vaultmp/commit/f4c84dc8279770eb56e87c982ed7158906df11e5 inside your repository
2) create a new branch from there, make the necessary changes
3) submit a PR for that branch (to be merged into this repositories master)
4) then I will merge the PR here and you can merge upstream master (this repositories master) into your own master

**Comment by Sh1ft0x0EF** [comment]
Nice idea

**Comment by Sh1ft0x0EF** [comment]
What about 

> source\vaultserver\data\fallout3.sqlite3

file? 63MB

**Comment by foxtacles** [comment]
that is needed by the server, but it could also be refactored outside the repository

**Comment by Sh1ft0x0EF** [comment]
Does it contain data that cannot be generated?

**Comment by foxtacles** [comment]
it contains all kinds of entity/game information (such as valid items, locations, everything) - it was originally extracted from the game files and then compiled into this database so the server can easily read it

**Comment by Sh1ft0x0EF** [comment]
Oh, now I got it
Well, it only needed at runtime so I'll archive it too

**Comment by Sh1ft0x0EF** [comment]
-81MB
Not bad

**Comment by Sh1ft0x0EF** [comment]
Here's archive with all dll/exe files ripped + data files needed only at runtime
https://github.com/Sh1ft0x0EF/vaultmp/releases/tag/untagged-0aa212e7034126b47cce

**Comment by Sh1ft0x0EF** [comment]
Are we good to apply the PR? #145 
Or is there something I should fix?

**Comment by foxtacles** [comment]
it's good, but can you provide a link with the dependencies archive and add the link in the README.md?

**Comment by Sh1ft0x0EF** [comment]
I can add a notice about that
But I think that we should attach the archive to some release of the main repo (this)

My CMake branch is currently buildable in debug
I could finish the support for release and x64 compilers and provide it here so we can create a release "Gary 2.11" from it
Later releases will just reference the previous is no changes have been made on that archive ([CryTek](https://github.com/CRYTEK/CRYENGINE/releases) is using the same approach)
The same branch fixes the RakNet submodule to build it properly

Whaddaya think about that?

**Comment by Sh1ft0x0EF** [comment]
I think that we should split the archive into two parts - client and server
