### ISSUE TITLE
CMake and newer compiler versions support

### ISSUE THREAD

**Issue by BlackPhrase** [foxtacles/vaultmp#146]
Tried to build the project with MinGW-w64 7.1.0

My CMakeLists are still WIP but so far I was able to build the vaultmpdll and vaultscript
I didn't try to build source/lib submodules yet
vaultmaster is compilable but fails at linking stage for now
vaultserver is broken (+ boost::any was replaced with std::any and this module now requires C++17)
vaultmp.exe fails to compile Game.cpp because of substitution failure using GameFactory::Get methods
Mostly it fails because of the next line:
https://github.com/VaultTecWorkshop/vaultmp-vtw/blob/cmake-support/source/GameFactory.hpp#L205
(UPD: it fails at GameFactory's Get and Operate methods)

This is the only broken file + stack.cpp has some weird situation - it couldn't find bfd.h which is located in "mingw/include" folder (fixed with temporary(?) hack):
https://github.com/VaultTecWorkshop/vaultmp-vtw/blob/cmake-support/source/CMakeLists.txt#L51

Without the Game.cpp compilation vaultmpd.exe fails at linking

**Comment by Sh1ft0x0EF** [comment]
https://github.com/Sh1ft0x0EF/vaultmp/tree/b5c8a1629f5d2bf88d92716f50689b130558a043
Everything except for vaultserver is currently buildable in debug
Broken parts of Game.cpp were commented out for now

**Comment by Sh1ft0x0EF** [comment]
https://github.com/Sh1ft0x0EF/vaultmp/commit/d3943c6fdc907f62e49bc4ada52c5bd4fbddb532
Built the amx library
Fixed the vaultserver build
Looks like vaultmaster is working but I can't be sure atm
vaultmpd requires F3 redist to test it out
vaultserver is crashing with:
`BFD: Dwarf Error: Could not find abbrev number 3772`
