### ISSUE TITLE
This thing is broken

### ISSUE THREAD

**Issue by BlackPhrase** [foxtacles/vaultmp#152]
I was able to run the Gary 2.15
At first, it did run well but crashed after I tried to shoot from the gun (both 10mm and thrower are causing crash right before the muzzle flash should be drawn on screen; fists are fine)
It also has some issues with race selection
Most of the time I saw myself as a ghoul and a human once (but that time the debug menu didn't open)
Also tried to spawn a guy and crashed
Now it crashes a couple seconds after map loaded
This is caused by the "vaultcast failed" errors and std::future timeout in 5s for some packet sending
I'll try to figure out the cause of that but atm it's really unstable
Well
At least it works...

**Comment by Sh1ft0x0EF** [comment]
Yep, crashes here:
https://github.com/foxtacles/vaultmp/blob/f4c84dc8279770eb56e87c982ed7158906df11e5/source/Game.cpp#L726

**Comment by Sh1ft0x0EF** [comment]
That might be caused by the usage of the new compiler...
It's probably using the default policy set to 

> future_status::deferred

 instead of 

> future_status::async

**Comment by Sh1ft0x0EF** [comment]
Tried with stutter remover - works
I'm still a man ghoul and sex selection seems doesn't work
Making a fatman explosion leads to a crash
Drink beer does nothing

**Comment by Dokman** [comment]
this is no longer supported
